version: '3'
volumes:
  data-vol:

services:
  builder:
    build: builder
    volumes:
      - "data-vol:/opt/tomcat/latest/webapps"
    
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MARIADB_DATABASE: dd
      MARIADB_USER: acp4pogynvaeidfj
      MARIADB_PASSWORD: jc31d2qyy7h9jv5jn1u9uosjksxzaizw
    ports:
      - "3306:3306"


  tomcat:
    build: service
    depends_on:
      - builder
    ports: 
      - "8080:8080"
    volumes:
       - "data-vol:/opt/tomcat/webapps/"
